services:
  - type: web
    name: fashionton-backend
    runtime: node
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: UPSTASH_REDIS_REST_URL
        value: https://ultimate-ape-39168.upstash.io
      - key: UPSTASH_REDIS_REST_TOKEN
        value: AZkAAAIncDIxZjNkMTFjMTYyYzQ0ZWY4YTgxNDgwNjMwMTc5ZDVmMHAyMzkxNjg
      - key: TELEGRAM_BOT_TOKEN
        value: 8045165561:AAGOknrIrvhNo5eG8SGX06bbY49aMN0Xfq4
      - key: NODE_ENV
        value: production
